export const ACTION_CONSTANTS = {
  SET_INPUT: 'setInput',
  ADD_TODO: 'addTodo',
  ADD_TODO_SUCCESS: 'addTodoSuccess',
  ADD_TODO_FAILURE: 'addTodoFailure',
  UPDATE_TODO: 'updateTodo',
  UPDATE_TODO_SUCCESS: 'updateTodoSuccess',
  UPDATE_TODO_FAILURE: 'updateTodoFailure',
  SELECT_TODO: 'selectTodo',
  DELETE_TODO: 'deleteTodo',
  DELETE_TODO_SUCCESS: 'deleteTodoSuccess',
  DELETE_TODO_FAILURE: 'deleteTodoFailure',
  DESCRIPTION: 'description',
  STATUS_DONE: 'completed',
  FETCH_TODOS: 'todos/fetch',
  RECEIVE_TODOS_SUCCESS: 'todos/fetchSuccess',
  RECEIVE_TODOS_FAILURE: 'todos/fetchfailure',
  TRIGGER_DATA_LOADING: 'todos/loading',
  TRIGGER_TODO_LOADING: 'todo/loading',
};
