export const ACTION_CONSTANTS = {
  SET_INPUT: 'setInput',
  ADD_TODO: 'addTodo',
  UPDATE_TODO_DESC: 'updateTodo',
  UPDATE_TODO_STATUS: 'updateTodoStatus',
  SORT_TODOS: 'sortTodos',
  SELECT_TODO: 'selectTodo',
  REMOVE_TODO: 'removeTodo',
  DESCRIPTION: 'description',
  STATUS_DONE: 'statusDone',
  VALUE_EXISTS: 'A similar todo allready exists',
  FETCH_TODOS: 'todos/fetch',
  RECEIVE_TODOS_SUCCESS: 'todos/fetchSuccess',
  RECEIVE_TODOS_FAILURE: 'todos/fetchfailure',
  TRIGGER_LOADING: 'todos/loading',
};
